baseURL = 'https://blog.viticlin.com/'
title = "Viticlin's Blog"
theme = 'risotto'
author = 'Víctor Fernández'
copyright = "Nothing here"
pagination.pagerSize = 3
languageCode = 'en'
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
enableInlineShortcodes = true

# Automatically add content sections to main menu
sectionPagesMenu = "main"

# For GitHub Pages
[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
noindex = false

[params.theme]
palette = "base16-dark"

# Sidebar: about/bio
[params.about]
title = "Blog"
description = "Here you'll find things I learn and want to share 😄"
# or use an image:
#logo_image = "images/rice.svg"

# Sidebar: social links
# Available icon sets:
# * FontAwesome 6 <https://fontawesome.com/> ('fa-brands', 'fa-normal', or 'fa-solid' for brands)
# * Academicons <https://jpswalsh.github.io/academicons> ('ai ai-')

[[params.socialLinks]]
icon = "fa-brands fa-github"
title = "GitHub"
url = "https://github.com/victor23k/"

[[params.socialLinks]]
icon = "fa-brands fa-linkedin"
title = "LinkedIn"
url = "https://github.com/victor23k/"

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

# For hugo >= 0.60.0, enable inline HTML
[markup.goldmark.renderer]
unsafe = true

[markup]

  # Table of contents
  # Add toc = true to content front matter to enable
  [markup.tableOfContents]
    startLevel = 2
    endLevel   = 3
    ordered    = true
